module.exports = {
  lights: {
    '1': {
      state: {
        on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        xy: [0.0, 0.0],
        ct: 0,
        alert: 'none',
        effect: 'none',
        colormode: 'hs',
        reachable: true,
      },
      type: 'Extended color light',
      name: 'Hue Lamp 1',
      modelid: 'LCT001',
      manufacturername: 'Philips',
      uniqueid: '66:11:38:22:28:3b:8d:6f-0b',
      swversion: '65003148',
      pointsymbol: {
        '1': 'none',
        '2': 'none',
        '3': 'none',
        '4': 'none',
        '5': 'none',
        '6': 'none',
        '7': 'none',
        '8': 'none',
      },
    },
    '2': {
      state: {
        on: true,
        bri: 254,
        hue: 33536,
        sat: 144,
        xy: [0.346, 0.3568],
        ct: 201,
        alert: 'none',
        effect: 'none',
        colormode: 'hs',
        reachable: true,
      },
      type: 'Extended color light',
      name: 'Hue Lamp 2',
      modelid: 'LCT001',
      manufacturername: 'Philips',
      uniqueid: 'c4:03:ae:98:28:d8:cc:af-0b',
      swversion: '65003148',
      pointsymbol: {
        '1': 'none',
        '2': 'none',
        '3': 'none',
        '4': 'none',
        '5': 'none',
        '6': 'none',
        '7': 'none',
        '8': 'none',
      },
    },
  },
  groups: {
    '1': {
      action: {
        on: true,
        bri: 254,
        hue: 33536,
        sat: 144,
        xy: [0.346, 0.3568],
        ct: 201,
        effect: 'none',
        colormode: 'xy',
      },
      lights: ['1', '2'],
      name: 'Group 1',
    },
  },
  config: {
    name: 'Philips hue',
    mac: '00:00:88:00:bb:ee',
    dhcp: true,
    ipaddress: '192.168.1.74',
    netmask: '255.255.255.0',
    gateway: '192.168.1.254',
    proxyaddress: '',
    proxyport: 0,
    UTC: '2012-10-29T12:00:00',
    whitelist: {
      newdeveloper: {
        'last use date': '2012-10-29T12:00:00',
        'create date': '2012-10-29T12:00:00',
        name: 'test user',
      },
    },
    swversion: '01003542',
    swupdate: {
      updatestate: 0,
      url: '',
      text: '',
      notify: false,
    },
    linkbutton: false,
    portalservices: false,
  },
  schedules: {},
}
